### ISSUE TITLE
Google error when trying to link account

### ISSUE THREAD

**Issue by conjalka** [iMicknl/ha-nest-protect#312] opened 2024-02-26 00:06 UTC
### The problem

When I attempt to use the "authorize your account" link to add the Nest Protect Integration, I get an error message:

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.2.3

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by Madj42** [comment] 2024-02-27 04:49
Same here.

**Comment by Madj42** [comment] 2024-02-27 05:21
I was able to work around this by upgrading to the beta using HACS and using the URL and cookie.

**Comment by iMicknl** [comment] 2024-02-27 08:11
Duplicate of #105. TLRDR: use beta.

**Closed by iMicknl** 2024-02-27 08:11 UTC
Labels: bug
