### ISSUE TITLE
Errors in ` _async_subscribe_for_data`

### ISSUE THREAD

**Issue by sambeetm** [iMicknl/ha-nest-protect#347] opened 2024-07-24 17:41 UTC
### The problem

Getting these errors in the logfile..

AttributeError: 'list' object has no attribute 'object_key'
2024-07-24 12:16:33.179 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b5

### What version of Home Assistant Core has the issue?

2024.7.3

### Device / Model

Topaz-2.7

### Home Assistant log

<details><summary>Logs</summary>

```
AttributeError: 'list' object has no attribute 'object_key'
2024-07-24 12:16:33.179 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
```
</details>

**Comment by jamesbont007** [comment] 2024-07-28 17:36
+1

**Comment by MikeBP13** [comment] 2024-07-29 17:52
+1

**Comment by dirixmjm** [comment] 2024-08-02 17:33
+1

**Comment by FeralSquid** [comment] 2024-08-03 02:33
+1

**Comment by FeralSquid** [comment] 2024-08-03 03:47
I'm not very familiar with python, but I believe the bug is the brackets around 'data.updated_buckets' here:

**Comment by dirixmjm** [comment] 2024-08-03 06:25
> I'm not very familiar with python, but I believe the bug is the brackets around 'data.updated_buckets' here:
> 
> ```
>     objects = [
>         dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
>     ]
> ```

Yes, this seems to solve the issue.

**Comment by dirixmjm** [comment] 2024-08-03 06:44
> I'm not very familiar with python, but I believe the bug is the brackets around 'data.updated_buckets' here:
> 
> ```
>     objects = [
>         dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
>     ]
> ```

Sorry, still get the same error after removing the brackets.

**Comment by iMicknl** [comment] 2024-08-03 07:13
Thanks all! Known issue, no need to keep reporting +1 (everyone on the latest version faces this 😉).

At the moment I don't have time to work on this unfortunately, but hope to make some time in the coming weeks. In the mean-time, contributions are appreciated.

**Comment by FeralSquid** [comment] 2024-08-03 16:41
yea, I'm having a hard time googling around to help parse that line of code and how it might be fixed, but based on the previous version and the comment above, I suspect the non-one-liner way to write what the intent is there would be:

    objects: list[Bucket] = []
    for b in updated_buckets:
        new_data = buckets.get(b["object_key"], {})
        if (new_data != {}):
            objects.append(cast(Bucket, new_data)) # not sure if cast is necessary here?
        else:
            objects.append(b) # I believe the intent is to keep around the old data if it isn't in the new result?

does that look right?

**Comment by ScottESanDiego** [comment] 2024-09-05 17:38
> does that look right?

That looks right to my eyes at first blush.  Have you had any luck with it working @FeralSquid ? (I don't see a PR, so assuming no time yet)

**Comment by therealmrfox** [comment] 2024-09-07 19:25
[Code](https://github.com/iMicknl/ha-nest-protect/issues/347#issuecomment-2266996025) above isn't quite right either:

```
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 223, in _async_subscribe_for_data
    new_data = buckets.get(b["object_key"], {})
                           ~^^^^^^^^^^^^^^
TypeError: 'Bucket' object is not subscriptable
```

**Comment by ScottESanDiego** [comment] 2024-09-08 17:07
Here's what seems to be working for me... I'm not sure why it works, but no errors and so far somewhat timely occupancy detection (which is what I'm trying to get):

```
        # Update buckets with new data, to only receive new updates
        buckets = {d["object_key"]: d for d in result["objects"]}

        LOGGER.debug(buckets)

        objects: list[Bucket] = []
        for b in data.updated_buckets:
            objects.append(b) # I believe the intent is to keep around the old data if it isn't in the new result?

        data.updated_buckets = objects
```        
 I'm not 100% convinced this is the right solution (or substantially any different than the original code!).

**Comment by ScottESanDiego** [comment] 2024-09-09 22:53
Submitted a PR for this https://github.com/iMicknl/ha-nest-protect/pull/355 (on the `beta` branch, although I think the same would apply to `main`)

**Comment by therealmrfox** [comment] 2024-09-10 05:46
With the patch above, I now get a different error:

```
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 164, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 91, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise BadCredentialsException(
custom_components.nest_protect.pynest.exceptions.BadCredentialsException: USER_LOGGED_OUT - No active session found.
```

Refreshing my `issue_token` and `cookies` didn't fix that. 

The funny thing is that the integration still works ok - Presence detection happens within a few seconds (with a 10-minute timeout before going back to clear, but I think that's expected?)

Maybe that _async_subscribe_for_data business isn't needed at all?

**Comment by thargy** [comment] 2024-09-29 17:54
@iMicknl in #358 you closed as duplicate saying,

>  It might be fixed in the main branch of this integration, but I haven't been able to test this myself yet.

However, the `main` branch has had no commits since January, and the `beta` hasn't had any commits since August. Where did you mean for us to look?

Perhaps #355?

**Comment by iMicknl** [comment] 2024-09-29 18:51
@thargy sorry, you are correct. It is indeed #355, I thought we already had this in the latest beta branch. 

I will merge it now and do a new release.

**Comment by ScottESanDiego** [comment] 2024-10-05 23:36
@iMicknl Ideas on how to fix this the right way?  I didn't notice the communication side-effect with my kludge.

**Comment by GSzabados** [comment] 2024-11-25 12:53
@iMicknl,

What is the logic here?

```
        result = await entry_data.client.subscribe_for_data(
            entry_data.client.nest_session.access_token,
            entry_data.client.nest_session.userid,
            data.service_urls["urls"]["transport_url"],
            data.updated_buckets,
        )

......

        # Update buckets with new data, to only receive new updates
        buckets = {d["object_key"]: d for d in result["objects"]}

        LOGGER.debug(buckets)

        objects = [
            dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
        ]

        data.updated_buckets = objects

        _register_subscribe_task(hass, entry, data)
```


What `objects` should contain at the end? Because I might have fixed the issue with the `AttributeError: 'list' object has no attribute 'object_key'` and `TypeError: 'Bucket' object is not iterable`, but now I have a different error from the pynest client: as ```
"object_key": bucket.object_key,
AttributeError: 'dict' object has no attribute 'object_key'
```

**Comment by GSzabados** [comment] 2024-11-26 13:53
@iMicknl, could you have a look on the PR regarding this issue and check if that still generates a lot of traffic to Google?

**Comment by iMicknl** [comment] 2024-12-08 21:19
Duplicate of #338

**Closed by iMicknl** 2024-12-08 21:19 UTC
Labels: bug
