### ISSUE TITLE
'Failed to set up'

### ISSUE THREAD

**Issue by aacentric** [iMicknl/ha-nest-protect#230] opened 2023-05-05 15:04 UTC
### The problem

Just today, Nest Protect stopped working in HA - got the 'failed to set up' red box.  Log:

2023-05-05 07:59:43.642 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nest Protect for nest_protect
File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry

Only change is updated to HA 2023.5.1.  Supervisor 2023.04.1, OS 10.1.  Tried removing and reinstalling add-on, no change.  Please help!

### What version of this integration (ha-nest-protect) has the issue?

0.1.0

### What version of Home Assistant Core has the issue?

2023.5.1

### Device / Model

Nest Protect Powered

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>
2023-05-05 07:59:43.642 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by iMicknl** [comment] 2023-05-05 16:13
Duplicate of #224. Please update your integration.

**Closed** 2023-05-10 20:39 UTC
Labels: bug
