### ISSUE TITLE
Out Of Band Flow Error - Cannot Authenticate

### ISSUE THREAD

**Issue by ShadowGames-Dev** [iMicknl/ha-nest-protect#288] opened 2023-12-23 19:28 UTC
### The problem

Getting the following error from the integration. 

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.12.3

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment] 2023-12-23 20:44
Work in progress. Please install latest beta version.

Duplicate of #105 (pinned issue..)

**Closed by iMicknl** 2023-12-23 20:44 UTC
Labels: bug
