### ISSUE TITLE
ERROR from nest protect HACS integration 

### ISSUE THREAD

**Issue by bmf7777** [iMicknl/ha-nest-protect#380] opened 2024-12-08 15:25 UTC
### The problem

ERROR from nest protect HACS integration

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b7

### What version of Home Assistant Core has the issue?

core-2024.12.1

### Device / Model

Nest Protect Wired

### Diagnostics information

2024-12-07 15:05:26.374 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with >
Traceback (most recent call last):                                                                                                      File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data            dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]                                                                                    ^^^^^^^^^^^^                                                                                                AttributeError: 'list' object has no attribute 'object_key'  

### Home Assistant log

<details><summary>Logs</summary>
2024-12-07 15:05:26.374 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with >
Traceback (most recent call last):                                                                                                      File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data            dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]                                                                                    ^^^^^^^^^^^^                                                                                                AttributeError: 'list' object has no attribute 'object_key'  
```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment] 2024-12-08 20:32
Duplicate of #347

**Closed by iMicknl** 2024-12-08 20:32 UTC
Labels: bug
