### ISSUE TITLE
Log Error: AttributeError: 'list' object has no attribute 'object_key'

### ISSUE THREAD

**Issue by tggman** [iMicknl/ha-nest-protect#377] opened 2024-12-02 13:24 UTC
### The problem

I just updated from b4 to b7 and started receiving the error in the logs 10 minutes after triggering the first occupancy.

Observations:
- The occupancy status failed to clear after the first 10m but did eventually clear after an addition 10min (20min total). 
- The error continues to be logged each time the occupancy status changes
- The error delays occupancy status changes
- Same issue occurs with the b5 version
- Issue goes away and the occupancy status is once again responsive after reverting back to the b4 version

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b7

### What version of Home Assistant Core has the issue?

2024.11.3

### Device / Model

Nest Protect Smoke and CO Detector Topaz-2.33 Firmware: 3.5rc3

### Home Assistant log

<details><summary>Logs</summary>

```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: 6:43:03 AM (2 occurrences)
Last logged: 6:48:03 AM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```
The error continues to make log entries:
```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: 6:43:03 AM (6 occurrences)
Last logged: 7:08:04 AM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```
</details>

**Comment by ablyler** [comment] 2024-12-06 12:49
I think this is a duplicate of #338

**Closed** 2024-12-08 21:18 UTC
Labels: bug
