### ISSUE TITLE
Access blocked: Nest's request is invalid error during initial setup

### ISSUE THREAD

**Issue by peteoheat** [iMicknl/ha-nest-protect#365] opened 2024-10-11 06:22 UTC
### The problem

When i click the link provided during installation to get an access token I get the above error. Reviewing the error details gives me the following:

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob flowName=GeneralOAuthFlow
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.10.1

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by Restitive** [comment] 2024-10-11 10:43
same problem

**Comment by iMicknl** [comment] 2024-10-11 11:37
Duplicate of #105. TLDR; use latest beta.

**Closed by iMicknl** 2024-10-11 11:37 UTC
Labels: bug
