### ISSUE TITLE
Nest Protect integration Error

### ISSUE THREAD

**Issue by jay23433** [iMicknl/ha-nest-protect#250] opened 2023-08-12 14:57 UTC
### The problem

When clicking on authorize your account to link my google account, I get an error message “ Access blocked: Nest’s request is invalid”

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.8.2

### Device / Model

Topaz-2.7

**Comment by iMicknl** [comment] 2023-08-13 09:31
Duplicate of #105.

TLDR: use beta version.

**Closed by iMicknl** 2023-08-13 09:31 UTC
Labels: bug

**Comment by jay23433** [comment] 2023-09-20 00:09
Thank you! I got an error with Beta version v0.4.0b2 but was able to make it work with v0.4.0b1.
