### ISSUE TITLE
Link to authorize Google account leads to an error

### ISSUE THREAD

**Issue by priteshm** [iMicknl/ha-nest-protect#270] opened 2023-11-06 23:41 UTC
### The problem

When clicking on the link on this dialog .... 
![image](https://github.com/iMicknl/ha-nest-protect/assets/1015719/d0b1c699-d768-442d-a912-de019efffef5)

it results in an error ...
![image](https://github.com/iMicknl/ha-nest-protect/assets/1015719/3bea3e79-9e28-4ddb-aa57-8765bc93519c)
![image](https://github.com/iMicknl/ha-nest-protect/assets/1015719/06039c12-b05b-47ae-b383-646293dc9ba8)

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.11.1

### Device / Model

Nest Protect (Wired)

### Diagnostics information

Clicking on one of the links for the developer leads to this page
https://support.google.com/accounts/answer/12379384

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by rafal98** [comment] 2023-11-07 16:00
Hi, exact same issue with same version. FYI, I select "Google Account", not "Google Account (test field)" but can't reselect it once I select the first.

**Comment by superpower10** [comment] 2023-11-10 08:41
Same here.

Somewhere it says you need to install the Beta version and use the Google Cookie method. 

So I tried it and installed v0.4.0b2

1. But there are no instruction on how to
2. The Integration Setup Screen doesn't tell what to insert where:
<img width="594" alt="Bildschirmfoto 2023-11-10 um 09 37 40" src="https://github.com/iMicknl/ha-nest-protect/assets/20533966/527040b2-4c48-4df2-a1ec-f75cd98832b1">

Is this integration even maintained? If so, than only the code not this GitHub Page with instructions.

**Comment by iMicknl** [comment] 2023-11-13 17:10
Duplicate of #105.

Yes, my time for this integration has been less in the last months, hence why the latest integration is still in beta. I hope to have some more time coming months to make the version stable again and release it as a stable version.

You could try an earlier beta version (4.0b1) to see if this is working. In your case it seems something goes wrong with the German translation. Perhaps it works when you switch your language to English temporarily.

**Closed by iMicknl** 2023-11-13 17:10 UTC
Labels: bug
