### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by Xiondewah** [iMicknl/ha-nest-protect#266] opened 2023-10-18 07:55 UTC
### The problem

When I attempt configuration and click to link my Google account, I select Authorise your account, and get the error.

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

Supervisor 2023.10.0

### Device / Model

Nest protect wired

### Diagnostics information

No diagnostics as can't set up.

### Home Assistant log

No logs as it's coming from Google.

### Additional information

Hope I've provided enough info.  Google provide this explanation:

https://support.google.com/accounts/answer/12379384

**Comment by Xiondewah** [comment] 2023-10-18 07:56
Also found this:

The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)

**Comment by smarthome01824** [comment] 2023-10-21 20:15
HI Xiondewah,

Did the above link get you what yo needed to actually get around this block.  I have been playing with this for a while and thinking I am going down a wrong path because I cannot get it to work

**Comment by iMicknl** [comment] 2023-10-21 20:33
Duplicate of #105. You need to use the beta version of this integration.

**Closed** 2023-10-21 20:32 UTC
Labels: bug

**Comment by chrismac99** [comment] 2023-10-24 10:57
Where can I find the beta version of this integration?

**Comment by iMicknl** [comment] 2023-10-24 11:13
See https://github.com/iMicknl/ha-nest-protect/releases. Or select pre release in HACS.

Yes, we need better documentation, but didn't had time for this yet :(
