### ISSUE TITLE
Access blocked: Nest’s request is invalid - Error 400: invalid_request

### ISSUE THREAD

**Issue by chris78664** [iMicknl/ha-nest-protect#301] opened 2024-01-16 23:36 UTC
### The problem

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

### What version of this integration (ha-nest-protect) has the issue?

3.1.2

### What version of Home Assistant Core has the issue?

core-2024.1.3

### Device / Model

N/A

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

### Additional information

Getting auth error trying to setup integration.  Already have Google Nest installed and working, just doesn't support Nest Protect

**Comment by titis14** [comment] 2024-01-17 19:28
Hi, I just did the 2024.1.3 update and I now have this error:
Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:80
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 20:23:24 (7 occurrences)
Last logged: 20:25:12
Unknown exception.

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 80, in async_setup_entry
    auth = await client.get_access_token_from_cookies(issue_token, cookies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT

**Comment by netrose** [comment] 2024-01-17 21:25
I have the same exact problem trying to connect to nest protect

**Comment by narrcom** [comment] 2024-01-17 23:44
It appears that google have changed the authorisation protocols, here is the relevant info for the developer...
[https://developers.google.com/identity/protocols/oauth2/resources/oob-migration](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)

**Comment by joelevi** [comment] 2024-01-18 18:31
Same error

**Comment by iMicknl** [comment] 2024-01-19 08:55
Duplicate of https://github.com/iMicknl/ha-nest-protect/issues/105 (pinned issue). TLDR: use the beta.

**Closed by iMicknl** 2024-01-19 08:55 UTC
Labels: bug
