### ISSUE TITLE
HA 2022.11 Beta - Unable to prepare setup for platform nest_protect.select: Platform not found

### ISSUE THREAD

**Issue by B-Hartley** [iMicknl/ha-nest-protect#108] opened 2022-10-28 07:01 UTC
### The problem

Unable to prepare setup for platform nest_protect.select: Platform not found (Exception importing custom_components.nest_protect.select).

Home Assistant 2022.11.0b1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221027.0 - latest

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

2022.11.0b1

### Diagnostics information

[config_entry-nest_protect-37818b8f1ee7ac1edbad7f1f7e109b2b.json.txt](https://github.com/iMicknl/ha-nest-protect/files/9885964/config_entry-nest_protect-37818b8f1ee7ac1edbad7f1f7e109b2b.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```
2022-10-28 07:55:13.418 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-10-28 07:55:31.608 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-10-28 07:57:15.739 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
```

</details>

**Comment by iMicknl** [comment] 2022-10-28 09:07
Duplicate of #106

**Closed by iMicknl** 2022-10-28 09:07 UTC
Labels: bug
