### ISSUE TITLE
Auth stop working, entered new cookie/token and no devices

### ISSUE THREAD

**Issue by DavidRSullivan** [iMicknl/ha-nest-protect#296] opened 2024-01-06 07:54 UTC
### The problem

Not sure what's going on here, I had to re-get my issue token and cookie, and it successfully logged in, but I have no devices.  I tried uninstalling Next Protect and reinstalling it (starting over), same issue.  It says no devices and entities.  Previously I had my temperature sensors, etc.

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b4

### What version of Home Assistant Core has the issue?

2023.12.4

### Device / Model

This is the issue, I should see temperator sensors.

### Home Assistant log

<details><summary>Logs</summary>
LOG:

This starts with re-loading the integration.

2024-01-05 23:37:32.010 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nest_protect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nest_protect/sensor.py", line 127, in async_setup_entry
  File "/config/custom_components/nest_protect/entity.py", line 115, in __init__
    ) -> None:
        ^^^^^^^
  File "/config/custom_components/nest_protect/entity.py", line 30, in __init__
    self.entity_description = description
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '00000000-0000-0000-9103-7ce4400beded'
2024-01-05 23:39:02.535 ERROR (MainThread) [homeassistant.components.xbox] Error requesting xbox data: 429, message='Too Many Requests', url=URL('https://peoplehub.xboxlive.com/users/me/people/batch/decoration/preferredcolor,detail,multiplayersummary,presencedetail')
2024-01-05 23:39:05.160 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2024-01-05 23:39:05.163 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2024-01-05 23:39:05.167 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2024-01-05 23:39:05.167 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2024-01-05 23:39:05.168 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2024-01-05 23:39:05.168 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
]
 
</details>

**Comment by iMicknl** [comment] 2024-01-06 14:31
```
2024-01-05 23:37:32.010 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nest_protect platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/nest_protect/sensor.py", line 127, in async_setup_entry
File "/config/custom_components/nest_protect/entity.py", line 115, in init
) -> None:
^^^^^^^
File "/config/custom_components/nest_protect/entity.py", line 30, in init
self.entity_description = description
^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '00000000-0000-0000-9103-7ce4400beded'
```

We have seen this error before, but haven't been able to debug this yet. Did you recently change the locations / room names?

Duplicate of https://github.com/iMicknl/ha-nest-protect/issues/239.

**Closed by iMicknl** 2024-01-06 14:31 UTC
Labels: bug

**Comment by DavidRSullivan** [comment] 2024-01-07 04:34
No, specifically what happened was my auth started failing (similar failure to current issues), and my devices were listed as no longer reporting.  I tried to fix the auth with no luck, I upgraded to the newest version, with no luck.  Then I deleted the existing devices that were no longer being reported (because of the failed auth), uninstalled everything, rebooted, reinstalled, got auth to work, rebooted and that is what you see in the log
