### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by TheShai1** [iMicknl/ha-nest-protect#370] opened 2024-11-19 20:41 UTC
### The problem

Access blocked: Nest’s request is invalid

This is what happens when I try to log in

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.11.2

### Device / Model

Nest Protect Wired

### Diagnostics information

Access blocked: Nest’s request is invalid

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

### Additional information

Access blocked: Nest’s request is invalid

**Comment by nicosaurus** [comment] 2024-11-21 17:51
I am also getting this error as of 11-21-24. Here is more info on the error from the Google account error page:

The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.

**Comment by michelelucente** [comment] 2024-11-22 13:44
I have the same issue. Below a screenshot of the error:
<img width="1054" alt="Screenshot 2024-11-22 alle 14 40 31" src="https://github.com/user-attachments/assets/8fc6cff2-0b4b-4e3e-bf65-577a8794df43">


And here are the error details:
```
Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob flowName=GeneralOAuthFlow
```

**Comment by hjbwerf78** [comment] 2024-11-23 14:54
Same here: Acces blocked: Nest's request is invalid

**Comment by rbeeren** [comment] 2024-11-24 10:06
Same issue here: Acces blocked: Nest's request is invalid

**Comment by iMicknl** [comment] 2024-11-24 16:33
Duplicate of #105. TLDR: use the latest beta version of this integration.

**Closed by iMicknl** 2024-11-24 16:33 UTC
Labels: bug
