### ISSUE TITLE
Error on connecting

### ISSUE THREAD

**Issue by kristofvand** [iMicknl/ha-nest-protect#350] opened 2024-08-10 12:14 UTC
### The problem

The installation via HACS worked perfectly. But after adding it to devices, after the selection screen selecting google account. You need to authorize your account. WHen clicking the link i get an error from google.

Access blocked: Nest’s request is invalid

You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://accounts.google.com/).
Error 400: invalid_request

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.8.0

**Comment by kristofvand** [comment] 2024-08-10 12:15
![Error 400](https://github.com/user-attachments/assets/375b04d3-e9be-4438-8ee5-b8d4b977b38c)

**Comment by PappyChappy1** [comment] 2024-08-10 14:56
I'm getting the same error

**Comment by DineshCyanam** [comment] 2024-08-11 00:27
+1 for the same error

**Comment by invite-frey** [comment] 2024-08-11 04:05
Same here...

**Comment by iMicknl** [comment] 2024-08-11 16:42
Duplicate of #105. TLDR: use the latest beta version.

**Closed by iMicknl** 2024-08-11 16:42 UTC
Labels: bug
