### ISSUE TITLE
Can’t authenticate google account 

### ISSUE THREAD

**Issue by HomeAssist87** [iMicknl/ha-nest-protect#359] opened 2024-09-29 18:49 UTC
### The problem

Hi when I go to authenticate my account google wont let me says to contact the developer and it blocks access to signing in 

### What version of this integration (ha-nest-protect) has the issue?

Latest

### What version of Home Assistant Core has the issue?

Core

### Device / Model

Nest protect wired

### Diagnostics information

![IMG_6312](https://github.com/user-attachments/assets/9383c021-9629-49c6-87d7-f588721938fd)

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

### Additional information

Can’t do anything

**Comment by iMicknl** [comment] 2024-09-29 18:53
Duplicate of #105. TLDR: use beta branch / latest pre-release

**Closed by iMicknl** 2024-09-29 18:53 UTC
Labels: bug
