### ISSUE TITLE
Access Blocked when requesting token

### ISSUE THREAD

**Issue by heckyps** [iMicknl/ha-nest-protect#373] opened 2024-11-24 16:07 UTC
### The problem

Hello!

Everytime I try to request a token to sign in to the integration I get the same error message "_Access Blocked_".
The rest of the text is: 
_You cannot log in because Nest has sent an invalid request. You can try again later or contact the developer to resolve this issue. More information about this error
If you are a Nest developer, please see the error details.
Error 400: invalid_request_
_Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Detalles de la solicitud: redirect_uri=urn:ietf:wg:oauth:2.0:oob flowName=GeneralOAuthFlow_

Link provided:
- https://support.google.com/accounts/answer/12917337?visit_id=638680609642076866-684322507&rd=1

How can I solve it?

Many thanks in advance

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.6.3

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment] 2024-11-24 16:33
Duplicate of #105. TLDR: use the latest beta version of this integration.

**Closed by iMicknl** 2024-11-24 16:33 UTC
Labels: bug
