### ISSUE TITLE
TEMP_CELSIUS was used, should us UnitOfTemperature.CELSIUS

### ISSUE THREAD

**Issue by lnaylor13** [iMicknl/ha-nest-protect#305] opened 2024-01-22 15:08 UTC
### The problem

Log message popping up about depreciated use of TEMP_CELCIUS... 

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 09:56:55 (1 occurrences)
Last logged: 09:56:55

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues

### What version of this integration (ha-nest-protect) has the issue?

 v0.4.0b4

### What version of Home Assistant Core has the issue?

2024.1.5

### Device / Model

Temperature sensor

### Diagnostics information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "6.1.63-haos-raspi",
    "supervisor": "2023.12.1",
    "host_os": "Home Assistant OS 11.4",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "mazda_lb80": {
      "version": "0.1.0",
      "requirements": [
        "pymazda==0.3.11"
      ]
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "lb80_mcs": {
      "version": "0.0.1",
      "requirements": [
        "pymazda==0.3.11"
      ]
    },
    "cync_lights": {
      "version": "1.0.1",
      "requirements": []
    },
    "deebot": {
      "version": "3.1.1",
      "requirements": [
        "deebot-client==4.1.0",
        "numpy>=1.23.2"
      ]
    },
    "govee_lan": {
      "version": "1.0.0",
      "requirements": [
        "govee-led-wez>=0.0.15"
      ]
    },
    "nest_protect": {
      "version": "0.4.0b4",
      "requirements": []
    },
    "eufy_security": {
      "version": "8.0.1",
      "requirements": [
        "websocket-client==1.4.2",
        "aiortsp==1.3.7"
      ]
    }
  },
  "integration_manifest": {
    "domain": "nest_protect",
    "name": "Nest Protect",
    "codeowners": [
      "@imicknl"
    ],
    "config_flow": true,
    "dhcp": [
      {
        "macaddress": "CCA7C1*"
      }
    ],
    "documentation": "https://github.com/imicknl/ha-nest-protect",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/imicknl/ha-nest-protect/issues",
    "requirements": [],
    "version": "0.4.0b4",
    "is_built_in": false
  },
  "data": {
    "device": {
      "controllable_name": null,
      "firmware": null,
      "model": "KR1"
    },
    "app_launch": {
      "2fa_enabled": true,
      "service_urls": {
        "limits": {
          "smoke_detectors": 54,
          "smoke_detectors_per_structure": 18,
          "structures": 5,
          "thermostats": 60,
          "thermostats_per_structure": 20
        },
        "urls": {
          "czfe_url": "https://czfe91-front01-iad01.transport.home.nest.com",
          "direct_transport_url": "https://transport02-rts29-iad01.transport.home.nest.com:443",
          "log_upload_url": "https://logsink.home.nest.com/upload/user",
          "rubyapi_url": "https://home.nest.com/",
          "support_url": "https://nest.secure.force.com/support/webapp?",
          "transport_url": "https://czfe91-front01-iad01.transport.home.nest.com",
          "weather_url": "https://apps-weather.nest.com/weather/v1?query="
        },
        "weave": {
          "access_token": "**REDACTED**",
          "pairing_token": "**REDACTED**",
          "service_config": "**REDACTED**"
        }
      },
      "updated_buckets": [
        {
          "object_key": "topaz.18B43000419901B2",
          "object_revision": -27736,
          "object_timestamp": 1705935000605,
          "value": {
            "auto_away": false,
            "auto_away_decision_time_secs": 600,
            "battery_health_state": 0,
            "battery_level": 5346,
            "buzzer_test_results": 16384,
            "capability_level": 2.0,
            "certification_body": 1,
            "co_blame_duration": 0,
            "co_blame_threshold": 0,
            "co_previous_peak": 3,
            "co_sequence_number": 0,
            "co_status": 0,
            "component_als_test_passed": true,
            "component_buzzer_test_passed": true,
            "component_co_test_passed": true,
            "component_heat_test_passed": false,
            "component_hum_test_passed": true,
            "component_led_test_passed": true,
            "component_pir_test_passed": true,
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "component_temp_test_passed": true,
            "component_us_test_passed": false,
            "component_wifi_test_passed": true,
            "creation_time": 1665947295328,
            "device_born_on_date_utc_secs": 1661212800,
            "device_external_color": "white",
            "device_locale": "en_US",
            "fabric_id": "CD13061A5C31B9C9",
            "gesture_hush_enable": false,
            "heads_up_enable": true,
            "heat_status": 0,
            "home_alarm_link_capable": false,
            "home_alarm_link_connected": false,
            "home_alarm_link_type": 0,
            "home_away_input": false,
            "hushed_state": false,
            "installed_locale": "en_US",
            "is_rcs_capable": false,
            "is_rcs_used": false,
            "kl_software_version": "3.4.5",
            "last_audio_self_test_end_utc_secs": 1704846097,
            "last_audio_self_test_start_utc_secs": 1704846094,
            "latest_manual_test_cancelled": false,
            "latest_manual_test_end_utc_secs": 1665947996,
            "latest_manual_test_start_utc_secs": 1665947941,
            "line_power_present": true,
            "model": "Topaz-2.33",
            "night_light_brightness": 2,
            "night_light_continuous": false,
            "night_light_enable": true,
            "ntp_green_led_brightness": 2,
            "ntp_green_led_enable": true,
            "product_id": 9,
            "removed_from_base": false,
            "replace_by_date_utc_secs": 1976832000,
            "resource_id": "topaz_resource.5",
            "serial_number": "**REDACTED**",
            "smoke_sequence_number": 0,
            "smoke_status": 0,
            "software_version": "3.5rc3",
            "speaker_test_results": 16384,
            "spoken_where_id": "00000000-0000-0000-0000-000100000010",
            "steam_detection_enable": true,
            "structure_id": "5ee63e13-4d85-11ed-9130-0eedd3c8eec5",
            "thread_ip_address": "**REDACTED**",
            "thread_mac_address": "**REDACTED**",
            "where_id": "00000000-0000-0000-0000-000100000010",
            "wifi_ip_address": "10.0.0.106",
            "wifi_mac_address": "**REDACTED**",
            "wifi_regulatory_domain": "A0",
            "wired_led_enable": true,
            "wired_or_battery": 0
          }
        },
        {
          "object_key": "where.5ee63e13-4d85-11ed-9130-0eedd3c8eec5",
          "object_revision": 9302,
          "object_timestamp": 1674068391896,
          "value": {
            "wheres": [
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000000"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000001"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000002"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000003"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000004"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000005"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000006"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000007"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000009"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000a"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000b"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000c"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000d"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000e"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000f"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000010"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000011"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000012"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000013"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000014"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000015"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000016"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000017"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000018"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001a"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001b"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001c"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001d"
              }
            ]
          }
        },
        {
          "object_key": "kryptonite.18B430C1E6952442",
          "object_revision": -28555,
          "object_timestamp": 1705935834484,
          "value": {
            "battery_level": 100,
            "current_temperature": 21.799988,
            "last_updated_at": 1705935834,
            "model": "KR1",
            "serial_number": "**REDACTED**",
            "structure_id": "9fdaf870-3b12-11eb-886b-0ea511e39c12",
            "where_id": "00000000-0000-0000-0000-00010000000d"
          }
        },
        {
          "object_key": "topaz.18B430004198F887",
          "object_revision": -12890,
          "object_timestamp": 1705934985743,
          "value": {
            "auto_away": true,
            "auto_away_decision_time_secs": 600,
            "battery_health_state": 0,
            "battery_level": 5288,
            "buzzer_test_results": 16384,
            "capability_level": 2.0,
            "certification_body": 1,
            "co_blame_duration": 0,
            "co_blame_threshold": 0,
            "co_previous_peak": 0,
            "co_sequence_number": 0,
            "co_status": 0,
            "component_als_test_passed": true,
            "component_buzzer_test_passed": true,
            "component_co_test_passed": true,
            "component_heat_test_passed": false,
            "component_hum_test_passed": true,
            "component_led_test_passed": true,
            "component_pir_test_passed": true,
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "component_temp_test_passed": true,
            "component_us_test_passed": false,
            "component_wifi_test_passed": true,
            "creation_time": 1667237444554,
            "device_born_on_date_utc_secs": 1661212800,
            "device_external_color": "white",
            "device_locale": "en_US",
            "fabric_id": "CD13061A5C31B9C9",
            "gesture_hush_enable": false,
            "heads_up_enable": true,
            "heat_status": 0,
            "home_alarm_link_capable": false,
            "home_alarm_link_connected": false,
            "home_alarm_link_type": 0,
            "home_away_input": false,
            "hushed_state": false,
            "installed_locale": "en_US",
            "is_rcs_capable": false,
            "is_rcs_used": false,
            "kl_software_version": "3.4.5",
            "last_audio_self_test_end_utc_secs": 1704846099,
            "last_audio_self_test_start_utc_secs": 1704846097,
            "latest_manual_test_cancelled": false,
            "line_power_present": true,
            "model": "Topaz-2.33",
            "night_light_brightness": 2,
            "night_light_continuous": false,
            "night_light_enable": true,
            "ntp_green_led_brightness": 2,
            "ntp_green_led_enable": true,
            "product_id": 9,
            "removed_from_base": false,
            "replace_by_date_utc_secs": 1976832000,
            "resource_id": "topaz_resource.5",
            "serial_number": "**REDACTED**",
            "smoke_sequence_number": 0,
            "smoke_status": 0,
            "software_version": "3.5rc3",
            "speaker_test_results": 16384,
            "spoken_where_id": "00000000-0000-0000-0000-000100000002",
            "steam_detection_enable": true,
            "structure_id": "5ee63e13-4d85-11ed-9130-0eedd3c8eec5",
            "thread_ip_address": "**REDACTED**",
            "thread_mac_address": "**REDACTED**",
            "where_id": "00000000-0000-0000-0000-000100000002",
            "wifi_ip_address": "10.0.0.122",
            "wifi_mac_address": "**REDACTED**",
            "wifi_regulatory_domain": "A0",
            "wired_led_enable": true,
            "wired_or_battery": 0
          }
        },
        {
          "object_key": "structure.5ee63e13-4d85-11ed-9130-0eedd3c8eec5",
          "object_revision": 15628,
          "object_timestamp": 1685610254646,
          "value": {
            "address_lines": "**REDACTED**",
            "aux_primary_fabric_id": "**REDACTED**",
            "away": false,
            "away_setter": 1,
            "away_timestamp": 1685482906,
            "clutches": [],
            "country_code": "CA",
            "devices": [],
            "dr_reminder_enabled": true,
            "enable_goose": false,
            "entitlements": {},
            "eta_preconditioning_active": false,
            "fabric_ids": [
              "CD13061A5C31B9C9"
            ],
            "geofence_enhanced_autoaway": {
              "enabled": true,
              "is_set": true
            },
            "goose_sensor_events_enabled": false,
            "hvac_safety_shutoff_enabled": true,
            "hvac_smoke_safety_shutoff_enabled": false,
            "ifj_primary_fabric_id": "**REDACTED**",
            "latitude": "**REDACTED**",
            "location": "**REDACTED**",
            "longitude": "**REDACTED**",
            "manual_away_timestamp": 1685482906,
            "manual_eco_all": false,
            "members": [
              {
                "roles": [
                  "owner"
                ],
                "user": "**REDACTED**"
              }
            ],
            "name": "**REDACTED**",
            "phone_hush_enable": true,
            "postal_code": "**REDACTED**",
            "rcs_sensor_swarm": [],
            "swarm": [
              "topaz.18B430004198F887",
              "topaz.18B43000419901B2"
            ],
            "time_zone": "**REDACTED**",
            "topaz_away": false,
            "topaz_enhanced_auto_away_enabled": false,
            "topaz_hush_key": "**REDACTED**",
            "touched_by": {
              "touched_by": 0,
              "touched_id": "",
              "touched_user_id": ""
            },
            "user": "**REDACTED**",
            "vacation_mode": false
          }
        },
        {
          "object_key": "kryptonite.18B430C70D45280D",
          "object_revision": 8172,
          "object_timestamp": 1705935512281,
          "value": {
            "battery_level": 100,
            "current_temperature": 22.799988,
            "last_updated_at": 1705935512,
            "structure_id": "9fdaf870-3b12-11eb-886b-0ea511e39c12",
            "where_id": "00000000-0000-0000-0000-00010000000c"
          }
        },
        {
          "object_key": "where.9fdaf870-3b12-11eb-886b-0ea511e39c12",
          "object_revision": 31541,
          "object_timestamp": 1607623675640,
          "value": {
            "wheres": [
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000000"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000001"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000002"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000003"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000004"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000005"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000006"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000007"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000009"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000a"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000b"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000c"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000d"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000e"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000000f"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000010"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000011"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000012"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000013"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000014"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000015"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000016"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000017"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-000100000018"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001a"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001b"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001c"
              },
              {
                "name": "**REDACTED**",
                "where_id": "00000000-0000-0000-0000-00010000001d"
              }
            ]
          }
        },
        {
          "object_key": "structure.9fdaf870-3b12-11eb-886b-0ea511e39c12",
          "object_revision": 14610,
          "object_timestamp": 1705864517794,
          "value": {
            "address_lines": "**REDACTED**",
            "away": false,
            "away_setter": 1,
            "away_timestamp": 1705792296,
            "campaign_id": "LSS_HEATING_PROD_20231109",
            "city": "**REDACTED**",
            "clutches": [],
            "country_code": "CA",
            "devices": [],
            "dr_reminder_enabled": true,
            "enable_goose": false,
            "entitlements": {},
            "eta_preconditioning_active": false,
            "fabric_ids": [
              "5EADA2735E0B241F"
            ],
            "geofence_enhanced_autoaway": {
              "enabled": true,
              "is_set": true
            },
            "goose_sensor_events_enabled": true,
            "hvac_safety_shutoff_enabled": true,
            "hvac_smoke_safety_shutoff_enabled": false,
            "ifj_primary_fabric_id": "**REDACTED**",
            "latitude": "**REDACTED**",
            "location": "**REDACTED**",
            "longitude": "**REDACTED**",
            "manual_away_timestamp": 1705864517,
            "manual_eco_all": false,
            "members": [
              {
                "roles": [
                  "member"
                ],
                "user": "**REDACTED**"
              },
              {
                "roles": [
                  "owner"
                ],
                "user": "**REDACTED**"
              }
            ],
            "name": "**REDACTED**",
            "phone_hush_enable": true,
            "postal_code": "**REDACTED**",
            "rcs_sensor_swarm": [
              "kryptonite.18B430C1E6952442",
              "kryptonite.18B430C70D45280D"
            ],
            "state": "**REDACTED**",
            "swarm": [
              "quartz.0304f03b74e443a59e1698b1a2b0cc3a",
              "kryptonite.18B430C1E6952442",
              "kryptonite.18B430C70D45280D"
            ],
            "time_zone": "**REDACTED**",
            "topaz_away": false,
            "topaz_enhanced_auto_away_enabled": false,
            "topaz_hush_key": "**REDACTED**",
            "touched_by": {
              "touched_by": 0,
              "touched_id": "",
              "touched_user_id": ""
            },
            "user": "**REDACTED**",
            "vacation_mode": false
          }
        }
      ],
      "weather_for_structures": {
        "structure.9fdaf870-3b12-11eb-886b-0ea511e39c12": {
          "current": {
            "icon": "mostlycloudy",
            "sunrise": "**REDACTED**",
            "sunset": "**REDACTED**",
            "temp_c": "**REDACTED**"
          },
          "location": "**REDACTED**"
        },
        "structure.5ee63e13-4d85-11ed-9130-0eedd3c8eec5": {
          "current": {
            "icon": "mostlycloudy",
            "sunrise": "**REDACTED**",
            "sunset": "**REDACTED**",
            "temp_c": "**REDACTED**"
          },
          "location": "**REDACTED**"
        }
      }
    }
  }
}

### Home Assistant log

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 09:56:55 (1 occurrences)
Last logged: 09:56:55

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues

**Comment by iMicknl** [comment] 2024-01-27 15:32
Duplicate of #290

**Closed by iMicknl** 2024-01-27 15:32 UTC
Labels: bug
