### ISSUE TITLE
Unknown exception in the log

### ISSUE THREAD

**Issue by betsim** [iMicknl/ha-nest-protect#356] opened 2024-09-15 06:45 UTC
### The problem

I do not experienced any issues - just this log entry

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.9.1

### Device / Model

Nest Protect (Battery) Firmware: 3.5rc3

### Home Assistant log

<details><summary>Logs</summary>

```
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```
</details>

**Comment by iMicknl** [comment] 2024-09-15 13:31
Duplicate of #347

**Closed by iMicknl** 2024-09-15 13:31 UTC
Labels: bug
