### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by matth08080808** [iMicknl/ha-nest-protect#358] opened 2024-09-29 07:20 UTC
### The problem

I am getting this error 300+ times

This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: 16:43:18 (1 occurrences)
Last logged: 16:43:18

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.9.3

### Device / Model

Topasz-2.9

### Diagnostics information

I get this error numerous times 500+ in a week

This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: 16:43:18 (2 occurrences)
Last logged: 16:48:20

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment] 2024-09-29 15:38
Duplicate of #347. It might be fixed in the main branch of this integration, but I haven't been able to test this myself yet.

**Closed by iMicknl** 2024-09-29 15:38 UTC
Labels: bug
