### ISSUE TITLE
AttributeError: 'list' object has no attribute 'object_key'

### ISSUE THREAD

**Issue by breniii** [iMicknl/ha-nest-protect#354] opened 2024-09-04 00:45 UTC
### The problem

2024-09-03 20:38:46.827 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

core-2024.8.3

### Home Assistant log

<details><summary>Logs</summary>

```
2024-09-03 20:38:46.827 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'```
</details>


### Additional information

_No response_

**Comment by jasonanovak** [comment] 2024-09-04 00:51
I think this is a dupe of https://github.com/iMicknl/ha-nest-protect/issues/347

**Comment by iMicknl** [comment] 2024-09-08 20:57
Duplicate of #347

**Closed by iMicknl** 2024-09-08 20:57 UTC
Labels: bug
