### ISSUE TITLE
Motion Detected Delayed

### ISSUE THREAD

**Issue by brooksben11** [iMicknl/ha-nest-protect#349] opened 2024-08-04 12:50 UTC
### The problem

I've used this integration for years but a few months ago it started taking a couple minutes for motion to show up in HA. If I reload the integration, it immediately shows motion as detected, but left to it's own it take a few minutes. I'm guessing this may be true for other sensors as well, but obviously can't easily test this. I've found it to be true for multiple Nests, I assume all of them (all of mine are mains powered). I have multiple instances of this error in my logs and I suspect the 5 minute timeout may be to blame.

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.6.4

### Device / Model

Nest Protect (wired)

### Diagnostics information

[config_entry-nest_protect-1c5c7254310722dbacc74f6a942d246c.json](https://github.com/user-attachments/files/16487592/config_entry-nest_protect-1c5c7254310722dbacc74f6a942d246c.json)

### Home Assistant log

This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: August 3, 2024 at 7:52:51 PM (143 occurrences)
Last logged: 7:43:55 AM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

**Comment by iMicknl** [comment] 2024-08-04 15:22
Most likely a duplicate of https://github.com/iMicknl/ha-nest-protect/issues/347

**Comment by IceBotYT** [comment] 2024-12-07 19:16
I'm having this issue too. How can I help troubleshoot? I can provide logs or anything you'd like.

**Comment by iMicknl** [comment] 2024-12-08 20:32
Duplicate of #347

**Closed by iMicknl** 2024-12-08 20:32 UTC
Labels: bug
