### ISSUE TITLE
Access blocked when trying to configure integration

### ISSUE THREAD

**Issue by ArLo69** [iMicknl/ha-nest-protect#133] opened 2023-01-14 15:05 UTC
### The problem

When I want to authorize my account to get a token, Google blocks access due to an 400 Error: Invalid request.

Detailed error:
Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Details of request: redirect_uri=urn:ietf:wg:oauth:2.0:oob
![2023-01-14 16_03_21-Sign in - Google Accounts](https://user-images.githubusercontent.com/90417431/212478605-10fa50d7-c8e7-43a5-9aac-e1e0a0c77758.png)

### What version of this integration (ha-nest-protect) has the issue?

0.1.0

### What version of Home Assistant Core has the issue?

2023.1.4

### Device / Model

Nest Protect (line power)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment] 2023-01-14 16:26
Duplicate of #105

**Closed by iMicknl** 2023-01-14 16:26 UTC
Labels: bug
