### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by b00reiland** [iMicknl/ha-nest-protect#126] opened 2023-01-02 17:36 UTC
### The problem

Whenever I try to configure the Integration, I'm being asked to authorize my account. When I click the link, I get  a 400 error 

I'm using 
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1

I think I'm on the latest Nest Protect integration but I can't check. I downloaded it on Nov 30th using the automated install.

### What version of this integration (ha-nest-protect) has the issue?

0.3.10

### What version of Home Assistant Core has the issue?

2022.12.8

### Device / Model

Nest Protect Battery

### Diagnostics information

No option to download diagnotics - I guess because the integration fails to get configured.

### Home Assistant log

<details><summary>Logs</summary>
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.28.4",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.3.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "b20e33c",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": false
    },
    "errors": [],
    "device": {
      "uiid": 3026,
      "params": {
        "bindInfos": "***",
        "subDevId": "967a1129004b12003026",
        "parentid": "10011a11d5",
        "lock": 0,
        "trigTime": "1671107128629",
        "battery": 100,
        "supportPowConfig": 1
      },
      "model": "ZIGBEE_DOOR_AND_WINDOW_SENSOR",
      "online": false,
      "localtype": null,
      "deviceid": "a480043454"
    }
  }
}

</details>

**Comment by AlexxIT** [comment] 2023-01-02 18:03
Why did you add SonoffLAN diagnostics to this issue?

**Comment by b00reiland** [comment] 2023-01-02 20:40
Hmmm good question. I wanted to add the complete Home Assistant log. Went to Settings - Logs and then choose to download complete log. That's what I pasted here.
If you can guide me on how to get the log for the Nest Protect integration that would be helpful.

**Comment by b00reiland** [comment] 2023-01-02 20:59
I've found this in the log, but nothing else regarding nest protect
2023-01-02 21:55:46.928 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by iMicknl** [comment] 2023-01-03 01:28
Duplicate of }
#105.

**Closed by iMicknl** 2023-01-03 01:28 UTC
Labels: bug
