### ISSUE TITLE
0.3.9 dont updetae becauseits say ther i have ha 2022.11.0 but uapdate require 2022.11

### ISSUE THREAD

**Issue by bmdadu** [iMicknl/ha-nest-protect#115] opened 2022-11-03 07:04 UTC
### The problem

0.3.9 dont updetae becauseits say ther i have ha 2022.11.0 but uapdate require 2022.11

### What version of this integration (ha-nest-protect) has the issue?

0.3.9

### What version of Home Assistant Core has the issue?

core-

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment] 2022-11-03 08:44
Duplicate of #112.

**Closed by iMicknl** 2022-11-03 08:44 UTC
Labels: bug
