### ISSUE TITLE
no motion detection

### ISSUE THREAD

**Issue by Christianb233** [iMicknl/ha-nest-protect#49] opened 2022-03-13 20:49 UTC
### The problem

The 'occupancy' sensor stays 'RAS' (nothing to declare in french) even if there is a motion in front of the Nest Protect

### What version of this integration (ha-nest-protect) has the issue?

0.3.2

### What version of Home Assistant Core has the issue?

core-2022.3.3

### Device / Model

Topaz-2.7 Firmware: 3.4rc6 Matériel : Battery

### Home Assistant log

<details><summary>Logs</summary>
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:242
Integration: Nest Protect (documentation, issues)
First occurred: 16:20:57 (5 occurrences)
Last logged: 21:31:00

Subscriber: pynest exception.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 238, in subscribe_for_data
    result = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://czfe71-front01-iad01.transport.home.nest.com/v6/subscribe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 128, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 242, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 504 error while subscribing - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>


```

</details>

**Comment by altodd** [comment] 2022-03-13 20:54
The battery version of the nest protect doesn't offer occupancy. We will be looking at how to hide this feature if a nest is battery-powered. For now, you can ignore it.

**Comment by iMicknl** [comment] 2022-03-13 20:59
Duplicate of https://github.com/iMicknl/ha-nest-protect/issues/48. Let's continue the discussion there.

@Christianb233 it would be great if you could include your diagnostics file. I would like to understand which values are different for your device.

**Closed by iMicknl** 2022-03-13 20:59 UTC
Labels: bug

**Comment by Christianb233** [comment] 2022-03-13 22:00
@iMicknl do you refer to these information in the device page ?
![image](https://user-images.githubusercontent.com/65049842/158081015-176d8323-e0ed-4ae5-b81c-7c1003688380.png)

**Comment by iMicknl** [comment] 2022-03-13 22:01
No, on the left side there should be a button to download diagnostic information. 

<img width="363" alt="Screen Shot 2022-03-13 at 23 01 29" src="https://user-images.githubusercontent.com/1424596/158081083-0a547b0e-617b-45b3-bfc3-b71684f490d7.png">

**Comment by Christianb233** [comment] 2022-03-13 22:32
yes found !
```
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.3.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.10.92-v7l+",
    "supervisor": "2022.03.3",
    "host_os": "Raspbian GNU/Linux 11 (bullseye)",
    "docker_version": "20.10.12",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "ezviz_cloud": {
      "version": "0.0.9.4",
      "requirements": [
        "pyezviz==0.2.0.6"
      ]
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "pollens": {
      "version": "2022.02.01",
      "requirements": []
    },
    "ssh": {
      "version": "0.1.5",
      "requirements": [
        "pexpect==4.6.0"
      ]
    },
    "googlewifi": {
      "version": "0.1.30",
      "requirements": [
        "googlewifi==0.0.20",
        "grpcio==1.44.0"
      ]
    },
    "prixCarburant": {
      "version": "1.1",
      "requirements": [
        "Prix-Carburant-FR-Client==1.0.3"
      ]
    },
    "hpprinter": {
      "version": "1.0.6",
      "requirements": [
        "xmltodict==0.12.0"
      ]
    },
    "keyatome": {
      "version": "5.2.0",
      "requirements": [
        "pykeyatome==1.4.1"
      ]
    },
    "variable": {
      "version": "2.2.1",
      "requirements": []
    },
    "monitor_docker": {
      "version": "1.10",
      "requirements": [
        "aiodocker==0.21.0",
        "python-dateutil==2.8.2"
      ]
    },
    "smartir": {
      "version": "1.17.5",
      "requirements": [
        "aiofiles==0.6.0"
      ]
    },
    "ble_monitor": {
      "version": "7.9.7",
      "requirements": [
        "pycryptodomex>=3.14.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.12",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "garbage_collection": {
      "version": "4.6",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "freebox_player": {
      "version": "1.0.6",
      "requirements": []
    },
    "nest_protect": {
      "version": "0.3.2",
      "requirements": []
    },
    "hacs": {
      "version": "1.23.0",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "deebot": {
      "version": "1.2.0",
      "requirements": [
        "deebot-client==1.2.1",
        "numpy>=1.21.2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "nest_protect",
    "name": "Nest Protect",
    "config_flow": true,
    "documentation": "https://github.com/imicknl/ha-nest-protect",
    "issue_tracker": "https://github.com/imicknl/ha-nest-protect/issues",
    "requirements": [],
    "codeowners": [
      "@imicknl"
    ],
    "iot_class": "cloud_polling",
    "version": "0.3.2",
    "dhcp": [
      {
        "macaddress": "CCA7C1*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "device": {
      "controllable_name": "Battery",
      "firmware": "3.4rc6",
      "model": "Topaz-2.7"
    },
    "app_launch": {
      "updated_buckets": [
        {
          "object_key": "topaz.18B4300000AF8A8D",
          "object_revision": 22863,
          "object_timestamp": 1647164121962,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-00010000000f",
            "creation_time": 1586616404343,
            "installed_locale": "fr_FR",
            "ntp_green_led_brightness": 2,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.1.30",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A1",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "00A1DACD1F02C57A",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "home_away_input": false,
            "device_locale": "fr_FR",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.16",
            "component_us_test_passed": false,
            "auto_away": true,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 16384,
            "wired_or_battery": 1,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1847750400,
            "certification_body": 2,
            "component_pir_test_passed": true,
            "structure_id": "b2d7a5b2-7b62-11ea-83b7-0aeed58cb786",
            "software_version": "3.4rc6",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 2,
            "device_external_color": "white",
            "smoke_status": 0,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 0,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-00010000000f",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "18b4300000af8a8d",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 16384,
            "wifi_mac_address": "18b430b3c460",
            "line_power_present": false,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1532131200,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5258
          }
        },
        {
          "object_key": "structure.b2d7a5b2-7b62-11ea-83b7-0aeed58cb786",
          "object_revision": -24097,
          "object_timestamp": 1647186431222,
          "value": {
            "swarm": [
              "topaz.18B4300000AF8A8D",
              "topaz.18B4300000AF912C"
            ],
            "manual_away_timestamp": 1647186429,
            "geofence_enhanced_autoaway": {
              "enabled": true,
              "is_set": true
            },
            "name": "**REDACTED**",
            "eta_preconditioning_active": false,
            "creation_time": 1586547442681,
            "location": "**REDACTED**",
            "touched_by": {
              "touched_by": 1,
              "touched_id": "",
              "touched_user_id": "user.19192702"
            },
            "latitude": "**REDACTED**",
            "ifj_primary_fabric_id": "**REDACTED**",
            "away_timestamp": 1647186430,
            "topaz_hush_key": "**REDACTED**",
            "enable_goose": false,
            "away_setter": 1,
            "phone_hush_enable": true,
            "hvac_safety_shutoff_enabled": true,
            "rcs_sensor_swarm": [],
            "longitude": "**REDACTED**",
            "aux_primary_fabric_id": "**REDACTED**",
            "topaz_enhanced_auto_away_enabled": false,
            "country_code": "FR",
            "hvac_smoke_safety_shutoff_enabled": false,
            "topaz_away": false,
            "vacation_mode": false,
            "fabric_ids": [
              "00A1DACD1F02C57A"
            ],
            "postal_code": "**REDACTED**",
            "entitlements": {},
            "dr_reminder_enabled": true,
            "members": [
              {
                "user": "user.19192702",
                "roles": [
                  "owner"
                ]
              }
            ],
            "manual_eco_all": false,
            "goose_sensor_events_enabled": true,
            "time_zone": "Europe/Paris",
            "user": "user.19192702",
            "clutches": [],
            "away": false,
            "devices": []
          }
        },
        {
          "object_key": "where.b2d7a5b2-7b62-11ea-83b7-0aeed58cb786",
          "object_revision": 2695,
          "object_timestamp": 1586547443829,
          "value": {
            "wheres": [
              {
                "where_id": "00000000-0000-0000-0000-00010000000c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000005",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000013",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000001",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000010",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001d",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000017",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000002",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000006",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000012",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000009",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000f",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000016",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000007",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000011",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000015",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000003",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000e",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000004",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000014",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000000",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000d",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000018",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001a",
                "name": "**REDACTED**"
              }
            ]
          }
        },
        {
          "object_key": "topaz.18B4300000AF912C",
          "object_revision": -5153,
          "object_timestamp": 1647143479077,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-000100000006",
            "creation_time": 1586616299225,
            "installed_locale": "fr_FR",
            "ntp_green_led_brightness": 2,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.1.31",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A1",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "00A1DACD1F02C57A",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "home_away_input": false,
            "device_locale": "fr_FR",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.16",
            "component_us_test_passed": false,
            "auto_away": true,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 0,
            "wired_or_battery": 1,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1847750400,
            "certification_body": 2,
            "component_pir_test_passed": true,
            "structure_id": "b2d7a5b2-7b62-11ea-83b7-0aeed58cb786",
            "software_version": "3.4rc6",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 2,
            "device_external_color": "white",
            "smoke_status": 0,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 0,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-000100000006",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "18b4300000af912c",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 0,
            "wifi_mac_address": "18b430b3a077",
            "line_power_present": false,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1532131200,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5193
          }
        }
      ],
      "service_urls": {
        "urls": {
          "rubyapi_url": "https://home.nest.com/",
          "czfe_url": "https://czfe93-front01-iad01.transport.home.nest.com",
          "log_upload_url": "https://logsink.home.nest.com/upload/user",
          "transport_url": "https://czfe93-front01-iad01.transport.home.nest.com",
          "weather_url": "https://apps-weather.nest.com/weather/v1?query=",
          "support_url": "https://nest.secure.force.com/support/webapp?",
          "direct_transport_url": "https://transport02-rts16-iad01.transport.home.nest.com:443"
        },
        "limits": {
          "thermostats_per_structure": 20,
          "structures": 5,
          "smoke_detectors_per_structure": 18,
          "smoke_detectors": 54,
          "thermostats": 60
        },
        "weave": {
          "service_config": "**REDACTED**",
          "pairing_token": "**REDACTED**",
          "access_token": "**REDACTED**"
        }
      },
      "weather_for_structures": {
        "structure.b2d7a5b2-7b62-11ea-83b7-0aeed58cb786": {
          "current": {
            "icon": "mostlycloudy",
            "temp_c": "7.8",
            "sunrise": "1647151800",
            "sunset": "1647193980"
          },
          "location": "**REDACTED**"
        }
      },
      "2fa_enabled": true
    }
  }
}
```
