### ISSUE TITLE
Unable to link Google Account

### ISSUE THREAD

**Issue by droolingtaz** [iMicknl/ha-nest-protect#128] opened 2023-01-05 16:26 UTC
### The problem

when I click on the authorize your account link I get the following error:
Access blocked: Nest’s request is invalid

### What version of this integration (ha-nest-protect) has the issue?

0.3.10

### What version of Home Assistant Core has the issue?

2023.1

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by Adesfire** [comment] 2023-01-05 17:13
Same here, when I click the "To link your Google account." it bring me to a "Access blocked: Nest’s request is invalid"
Details are:
`Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob `

Thank you in advance for whoever can help!

**Comment by ulanking** [comment] 2023-01-06 20:35
Same. #following

**Comment by foothook** [comment] 2023-01-08 17:23
Same. #following

**Comment by foothook** [comment] 2023-01-08 18:53
hi guys, not really a solution but a hint where you can find some information.
It seems google has recently discontinued the authentication method for nest.

There should be another workaround for make it work by retreiving an "authentication url" and "cookie"
this workaround is also described in the readme file that you find in this git...

hope this helps

more in this thread
https://github.com/chrisjshull/homebridge-nest/issues/575

**Comment by iMicknl** [comment] 2023-01-09 01:42
Duplicate of #105.

**Closed** 2023-01-09 01:42 UTC
Labels: bug
