### ISSUE TITLE
Error in HA log

### ISSUE THREAD

**Issue by MikeBP13** [iMicknl/ha-nest-protect#372] opened 2024-11-24 12:24 UTC
### The problem

I get constant errors in the logs and updates are paused. See log below.

### What version of this integration (ha-nest-protect) has the issue?

All

### What version of Home Assistant Core has the issue?

2024.11.3

### Device / Model

Nest Protect (Battery)

### Home Assistant log

<details><summary>Logs</summary>
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: 11:23:53 (35 occurrences)
Last logged: 14:14:44

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
</details>

**Comment by iMicknl** [comment] 2024-11-24 16:34
Duplicate of #338

**Closed by iMicknl** 2024-11-24 16:34 UTC
Labels: bug
