### ISSUE TITLE
Cannot auth to google: "request is invalid"

### ISSUE THREAD

**Issue by mmwagner02** [iMicknl/ha-nest-protect#156] opened 2023-02-09 22:09 UTC
### The problem

I have just installed (via HACS) this for the first time, and I am attempting to configure it.
When I click the 'authorize your account' link, I am directed to a page at on https://accounts.google.com which reads:

> ### Access blocked: Nest’s request is invalid
> You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
> If you are a developer of Nest, see [error details](https://accounts.google.com/).
> Error 400: invalid_request

The links on the error page seem to contain information about oath protocols and such, but that is not my forte.

I'd love to use this integration if I can get it to work!

### What version of this integration (ha-nest-protect) has the issue?

 v0.3.10

### What version of Home Assistant Core has the issue?

2023.2.3

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by esanuutinen** [comment] 2023-02-10 01:01
I have exactly the same issue.

**Comment by HabelStefan** [comment] 2023-02-10 05:55
Same problem on my side.

**Comment by iMicknl** [comment] 2023-02-10 08:00
Please look at the pinned issue.

Duplicate of #105.

**Closed by iMicknl** 2023-02-10 08:00 UTC
Labels: bug
