### ISSUE TITLE
Fout 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by PCR-2020** [iMicknl/ha-nest-protect#298] opened 2024-01-13 20:39 UTC
### The problem

Could be caused by the being part of the advanced protection program by Google (2 FA with physical key). 

Something is wrong with:
redirect_uri=https://my.home-assistant.io/redirect/oauth

Documentation reference:
https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.1.3

### Device / Model

N.a.

### Diagnostics information

See description

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by jasiegma** [comment] 2024-01-15 10:05
I am facing the same issue. 
`Fehler 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Anfragedetails: redirect_uri=urn:ietf:wg:oauth:2.0:oob`

**Comment by D3ezy** [comment] 2024-01-18 15:59
I am also having this issue. Running HACS 1.33.0 and HAOS Core 2024.1.3. Trying to authorize my Google Account via Chrome. 

```
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
```

**Comment by iMicknl** [comment] 2024-01-19 08:51
Duplicate of #105 (pinned issue). TLDR: use the beta.

**Closed by iMicknl** 2024-01-19 08:51 UTC
Labels: bug
