### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by MikeRaffety** [iMicknl/ha-nest-protect#129] opened 2023-01-07 23:31 UTC
### The problem

When clicking on the link in the Configure dialog, "To link your Google account, [authorize your account].", it gets this error instead:

Access blocked: Nest’s request is invalid

### What version of this integration (ha-nest-protect) has the issue?

 v0.3.10

### What version of Home Assistant Core has the issue?

2022.11.5

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment] 2023-01-08 05:16
Duplicate of #105

**Closed by iMicknl** 2023-01-08 05:16 UTC
Labels: bug
