### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by Pandabeer40** [iMicknl/ha-nest-protect#127] opened 2023-01-03 22:20 UTC
### The problem

When I try to install this integration, I have to retrieve a token - I choose the google account, choose voor authorize account - there is a new window opened where I see the next error message:

You can't log in because Nest sent an invalid request. Please try again later or contact the developer about this issue. Learn more about this error
If you're the developer of Nest, see the error details.
Error 400: invalid_request

Looking to this error
Fout 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Details van verzoek: redirect_uri=urn:ietf:wg:oauth:2.0:oob

Please can you help to solve this?

Thank you in advance

Peter

### What version of this integration (ha-nest-protect) has the issue?

latest

### What version of Home Assistant Core has the issue?

2022.12.9

### Device / Model

Nest Smoke Detector (230 v)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by gpf2ez** [comment] 2023-01-04 15:34
I am having the same issue.

**Comment by sebestenyb** [comment] 2023-01-04 21:50
me too

**Comment by iMicknl** [comment] 2023-01-05 00:56
Duplicate of #105

**Closed by iMicknl** 2023-01-05 00:56 UTC
Labels: bug
