### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by trouble2** [iMicknl/ha-nest-protect#168] opened 2023-02-25 07:38 UTC
### The problem

When click on the authorize your account link I get a message saying Access blocked: Nest’s request is invalid

You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://accounts.google.com/).
Error 400: invalid_request

### What version of this integration (ha-nest-protect) has the issue?

0.3.11

### What version of Home Assistant Core has the issue?

2023.2.4

### Device / Model

nest battery

**Comment by iMicknl** [comment] 2023-02-25 11:03
Duplicate of #105. (which I accidentally closed).

**Closed by iMicknl** 2023-02-25 11:03 UTC
Labels: bug

**Comment by deezid** [comment] 2024-04-04 13:33
Same issue here

**Comment by alexr544** [comment] 2024-08-11 00:59
Same issue here

**Comment by ajroads** [comment] 2024-09-01 13:07
Hi, I have same issue - is this likely to get resolved?

**Comment by iMicknl** [comment] 2024-09-01 20:42
See the linked issue. You will need the latest beta version.
