### ISSUE TITLE
Google authentication error

### ISSUE THREAD

**Issue by vijaysinh-patil** [iMicknl/ha-nest-protect#362] opened 2024-10-01 07:12 UTC
### The problem

![IMG_5783](https://github.com/user-attachments/assets/6daab394-75e3-4a88-a596-3534d946191f)
Unable to link account get token

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.8.3

### Device / Model

Nest protect wired 

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment] 2024-10-01 08:07
Duplicate of #105 (pinned issue). TLDR: use latest beta.

**Closed by iMicknl** 2024-10-01 08:07 UTC
Labels: bug
