### ISSUE TITLE
Home Assistant Error

### ISSUE THREAD

**Issue by cdn4lf** [iMicknl/ha-nest-protect#297] opened 2024-01-09 11:21 UTC
### The problem

Home assistant error requesting a bug report.  See below.

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 5:52:33 AM (1 occurrences)
Last logged: 5:52:33 AM

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b4

### What version of Home Assistant Core has the issue?

2024.01.01

### Diagnostics information

Error message for 2025.01.0

### Home Assistant log

<details><summary>Logs</summary>
```
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 5:52:33 AM (1 occurrences)
Last logged: 5:52:33 AM

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues
```

</details>

**Comment by iMicknl** [comment] 2024-01-13 13:46
Thanks for reporting. Duplicate of #290. Not an error by the way, just a warning and we will take care of this on time.

**Closed by iMicknl** 2024-01-13 13:46 UTC
Labels: bug
