### ISSUE TITLE
TEMP_CELSIUS deprecated, use UnitOfTemperature.CELSIUS instead

### ISSUE THREAD

**Issue by fvquicke** [iMicknl/ha-nest-protect#324] opened 2024-04-16 11:50 UTC
### The problem

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead

### What version of this integration (ha-nest-protect) has the issue?

v0.3.12

### What version of Home Assistant Core has the issue?

2024.4.3

### Device / Model

Topaz-2.33 door Google Firmware: 3.5rc3 Hardware: Battery

### Diagnostics information

WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration

### Home Assistant log

<details><summary>Logs</summary>

```
2024-04-15 12:53:44.841 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration
```
</details>

**Comment by bmos** [comment] 2024-04-18 22:13
Duplicate of #290

**Closed** 2024-04-21 19:10 UTC
Labels: bug
