### ISSUE TITLE
Attribute error - Async

### ISSUE THREAD

**Issue by thatguy55** [iMicknl/ha-nest-protect#225] opened 2023-05-04 12:44 UTC
### The problem

Issue with Async in HA OS 10+

Tested with 10 and 10.1

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

Home Assistant 2023.5.0 Supervisor 2023.04.1 Operating System 10.1 Frontend 20230503.1 

### Diagnostics information

Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 7:36:13 AM (1 occurrences)
Last logged: 7:36:13 AM

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by lweijl** [comment] 2023-05-04 12:46
Having this exact issue as well.

**Comment by Vinisz** [comment] 2023-05-04 12:47
I think you guys should check https://github.com/iMicknl/ha-nest-protect/issues/224

**Comment by iMicknl** [comment] 2023-05-04 12:55
Duplicate of #224.

**Closed by iMicknl** 2023-05-04 12:55 UTC
Labels: bug

**Comment by thatguy55** [comment] 2023-05-04 13:01
Agreed did not see. Thank you resolved

________________________________
