### ISSUE TITLE
Can't link Google Account

### ISSUE THREAD

**Issue by mikeyvt** [iMicknl/ha-nest-protect#174] opened 2023-03-01 14:05 UTC
### The problem

Tried to link my google account and getting a "Access Blocked" error.  I looked through other issues and didn't see this one.  Is this something new?  First time trying to connect.

![image](https://user-images.githubusercontent.com/33258406/222162819-dc486110-3684-4c26-8e13-2994af065b88.png)

![image](https://user-images.githubusercontent.com/33258406/222162858-a2285ab4-7850-43fd-ad98-34e8842b9bc8.png)

### What version of this integration (ha-nest-protect) has the issue?

0.3.11

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.5

### Diagnostics information

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment] 2023-03-01 14:06
Duplicate of #105 (pinned issue 😉)

**Closed by iMicknl** 2023-03-01 14:06 UTC
Labels: bug
