### ISSUE TITLE
Error list' object has no attribute 'object_key

### ISSUE THREAD

**Issue by cbandy7777** [iMicknl/ha-nest-protect#352] opened 2024-08-27 15:02 UTC
### The problem

Continual error in home assistant

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.8.3

### Device / Model

Nest protect wired

### Home Assistant log

This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: 5:36:44 AM (52 occurrences)
Last logged: 9:52:11 AM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

**Comment by janusn** [comment] 2024-08-28 19:55
I have having the same issue.

**Comment by iMicknl** [comment] 2024-08-28 21:44
Duplicate of #347

**Closed by iMicknl** 2024-08-28 21:44 UTC
Labels: bug
