### ISSUE TITLE
TEMP_CELSIUS is a deprecated constant 

### ISSUE THREAD

**Issue by sleaze** [iMicknl/ha-nest-protect#332] opened 2024-05-25 00:46 UTC
### The problem

```
2024-05-24 17:44:42.778 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-24 17:44:42.778 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-24 17:44:52.760 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues
```

Please fix <3

### What version of this integration (ha-nest-protect) has the issue?

current

### What version of Home Assistant Core has the issue?

2024.4.1

### Device / Model

Nest Protect (wired)

### Home Assistant log

<details><summary>Logs</summary>

```
2024-05-24 17:44:42.778 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-24 17:44:42.778 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-24 17:44:52.760 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues

```
</details>

**Comment by iMicknl** [comment] 2024-05-29 10:20
Duplicate of https://github.com/iMicknl/ha-nest-protect/issues/290

**Closed by iMicknl** 2024-05-29 10:20 UTC
Labels: bug
