### ISSUE TITLE
Cannot get access token

### ISSUE THREAD

**Issue by jhbehrens23** [iMicknl/ha-nest-protect#123] opened 2022-11-27 15:26 UTC
### The problem

When you press 'authorise your account' in configuration flow, Google throws the following error:

Access blocked: Nest’s request is invalid

name@email.com
You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://github.com/iMicknl/ha-nest-protect/issues/new?assignees=&labels=bug&template=bug_report.yml) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://github.com/iMicknl/ha-nest-protect/issues/new?assignees=&labels=bug&template=bug_report.yml).
Error 400: invalid_request

### What version of this integration (ha-nest-protect) has the issue?

latest

### What version of Home Assistant Core has the issue?

Home Assistant OS on RPi

### Device / Model

Nest Protect (Wired) with a Nest account migrated to Google

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment] 2022-11-27 15:36
Duplicate of https://github.com/iMicknl/ha-nest-protect/issues/105

**Closed by iMicknl** 2022-11-27 15:36 UTC
Labels: bug
