### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by awshirley** [iMicknl/ha-nest-protect#247] opened 2023-08-03 21:54 UTC
### The problem

No longer have access to my Nest Protects.  When trying to get a new access token, I see this error.

Access blocked: Nest’s request is invalid
You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://accounts.google.com/).
Error 400: invalid_request

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.08.0

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by aLTeReGo-SWI** [comment] 2023-08-04 21:01
I'm seeing this very same issue

**Comment by mcnijman** [comment] 2023-08-04 21:27
me too

**Comment by ORIOLESFan02** [comment] 2023-08-04 22:39
me three

**Comment by anartir** [comment] 2023-08-05 12:27
Same here.

**Comment by JAudi23** [comment] 2023-08-05 13:20
Have you tried the beta version?  Remove v3.12 and install v4.0b2

**Comment by ORIOLESFan02** [comment] 2023-08-05 13:53
> Have you tried the beta version? Remove v3.12 and install v4.0b2

I tried this and still got the same error. That's just me though.

**Comment by iMicknl** [comment] 2023-08-13 09:33
Duplicate of #105. TLDR: use beta version.

**Closed by iMicknl** 2023-08-13 09:33 UTC
Labels: bug

**Comment by ORIOLESFan02** [comment] 2023-08-13 14:58
> Duplicate of #105. TLDR: use beta version.

That didn't work either.
