### ISSUE TITLE
Reopening #168 - Nest's request is invalid (cannot authenticate)

### ISSUE THREAD

**Issue by Majestic7979** [iMicknl/ha-nest-protect#321] opened 2024-04-05 13:09 UTC
### The problem

See https://github.com/iMicknl/ha-nest-protect/issues/168

Today's date: April 5th 2024.

### What version of this integration (ha-nest-protect) has the issue?

Latest from HACS as of today's date

### What version of Home Assistant Core has the issue?

core-2024.4

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment] 2024-04-05 13:44
Duplicate of #105 (as mentioned in the issue you link to...)

**Closed** 2024-06-15 22:45 UTC
Labels: bug
